# Generated by Django 6.0.3 on 2026-03-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('content', models.TextField(default='We are dedicated to providing a divine sanctuary...')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
            ],
        ),
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='fa-solid fa-bell', help_text="FontAwesome icon class (e.g., 'fa-solid fa-bell')", max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Optional image instead of icon', null=True, upload_to='highlights/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomePageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Welcome to Kalyaneshwer Temple', max_length=200)),
                ('hero_subtitle', models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='home/')),
                ('cta_button_text', models.CharField(default='Book a Puja', max_length=50)),
                ('cta_button_link', models.CharField(default='/services/', max_length=200)),
                ('secondary_button_text', models.CharField(default='Learn More', max_length=50)),
                ('secondary_button_link', models.CharField(default='/about/', max_length=200)),
                ('support_title', models.CharField(default='Support Our Mission', max_length=200)),
                ('support_text', models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.')),
            ],
        ),
    ]
