# Generated by Django 6.0.3 on 2026-03-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutpagecontent_highlight_homepagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Event photo', null=True, upload_to='events/')),
                ('video_url', models.URLField(blank=True, help_text='Optional YouTube or Vimeo video link', null=True)),
                ('event_date', models.DateTimeField(help_text='When will this occur?')),
                ('location', models.CharField(blank=True, default='Kalyaneshwer Temple', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
    ]
