# Generated by Django 6.0.3 on 2026-03-27 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='content_en',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='content_hi',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='content_kn',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='title_en',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='title_hi',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='title_kn',
            field=models.CharField(default='About Us', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_hi',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_kn',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='title_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_hi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='galleryitem',
            name='title_kn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='description_hi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='description_kn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='title_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_button_text_en',
            field=models.CharField(default='Book a Puja', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_button_text_hi',
            field=models.CharField(default='Book a Puja', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='cta_button_text_kn',
            field=models.CharField(default='Book a Puja', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_subtitle_en',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_subtitle_hi',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_subtitle_kn',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_title_en',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_title_hi',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='hero_title_kn',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_button_text_en',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_button_text_hi',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='secondary_button_text_kn',
            field=models.CharField(default='Learn More', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_text_en',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_text_hi',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_text_kn',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_title_en',
            field=models.CharField(default='Support Our Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_title_hi',
            field=models.CharField(default='Support Our Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='support_title_kn',
            field=models.CharField(default='Support Our Mission', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='description_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_hi',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='title_kn',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_en',
            field=models.TextField(help_text='The value for this setting', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_hi',
            field=models.TextField(help_text='The value for this setting', null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='value_kn',
            field=models.TextField(help_text='The value for this setting', null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_hi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='description_kn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='name_kn',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_hi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_kn',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
