# Generated by Django 6.0.3 on 2026-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutpagecontent_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter / X'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=50, unique=True)),
                ('url', models.URLField(help_text='Full URL e.g. https://facebook.com/YourTemples')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = shown first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide from website')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', help_text='About page body text. Use new lines to create paragraphs.'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content_en',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', help_text='About page body text. Use new lines to create paragraphs.', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content_hi',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', help_text='About page body text. Use new lines to create paragraphs.', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='content_kn',
            field=models.TextField(default='We are dedicated to providing a divine sanctuary...', help_text='About page body text. Use new lines to create paragraphs.', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo shown alongside the about text', null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title',
            field=models.CharField(default='About Us', help_text='Main heading on the About page', max_length=200),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title_en',
            field=models.CharField(default='About Us', help_text='Main heading on the About page', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title_hi',
            field=models.CharField(default='About Us', help_text='Main heading on the About page', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='aboutpagecontent',
            name='title_kn',
            field=models.CharField(default='About Us', help_text='Main heading on the About page', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(help_text='Event details / description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_en',
            field=models.TextField(help_text='Event details / description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_hi',
            field=models.TextField(help_text='Event details / description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description_kn',
            field=models.TextField(help_text='Event details / description', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(help_text='Date and time of the event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Main event photo (shown as the card thumbnail)', null=True, upload_to='events/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', help_text='Venue / location of the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_en',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', help_text='Venue / location of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_hi',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', help_text='Venue / location of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_kn',
            field=models.CharField(blank=True, default='Kalyaneshwer Temple', help_text='Venue / location of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(help_text='Name of the event', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_en',
            field=models.CharField(help_text='Name of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_hi',
            field=models.CharField(help_text='Name of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title_kn',
            field=models.CharField(help_text='Name of the event', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='Main promotional video link (YouTube/Vimeo)', null=True),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for this photo', max_length=200),
        ),
        migrations.AlterField(
            model_name='eventimage',
            name='image',
            field=models.ImageField(help_text='Photo from this event', upload_to='event_gallery/'),
        ),
        migrations.AlterField(
            model_name='eventvideo',
            name='title',
            field=models.CharField(blank=True, help_text='Optional label for this video', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the gallery', null=True, upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title',
            field=models.CharField(blank=True, help_text='Optional caption', max_length=200),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title_en',
            field=models.CharField(blank=True, help_text='Optional caption', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title_hi',
            field=models.CharField(blank=True, help_text='Optional caption', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='galleryitem',
            name='title_kn',
            field=models.CharField(blank=True, help_text='Optional caption', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='description',
            field=models.TextField(help_text='A brief description shown on the homepage'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='description_en',
            field=models.TextField(help_text='A brief description shown on the homepage', null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='description_hi',
            field=models.TextField(help_text='A brief description shown on the homepage', null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='description_kn',
            field=models.TextField(help_text='A brief description shown on the homepage', null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='icon',
            field=models.CharField(default='fa-solid fa-bell', help_text="FontAwesome icon class (e.g., 'fa-solid fa-bell'). See fontawesome.com/icons", max_length=50),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image instead of using an icon', null=True, upload_to='highlights/'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order (lower = shown first)'),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title',
            field=models.CharField(help_text='Short title for this highlight', max_length=200),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title_en',
            field=models.CharField(help_text='Short title for this highlight', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title_hi',
            field=models.CharField(help_text='Short title for this highlight', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='title_kn',
            field=models.CharField(help_text='Short title for this highlight', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button_link',
            field=models.CharField(default='/services/', help_text='URL for the primary button (e.g. /services/)', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button_text',
            field=models.CharField(default='Book a Puja', help_text='Text for the primary call-to-action button', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button_text_en',
            field=models.CharField(default='Book a Puja', help_text='Text for the primary call-to-action button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button_text_hi',
            field=models.CharField(default='Book a Puja', help_text='Text for the primary call-to-action button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='cta_button_text_kn',
            field=models.CharField(default='Book a Puja', help_text='Text for the primary call-to-action button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Background image for the hero section', null=True, upload_to='home/'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', help_text='Subtitle text below the main heading'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle_en',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', help_text='Subtitle text below the main heading', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle_hi',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', help_text='Subtitle text below the main heading', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_subtitle_kn',
            field=models.TextField(default='A divine sanctuary for peace, prayer, and spiritual awakening.', help_text='Subtitle text below the main heading', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', help_text='Main heading shown in the hero section', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_en',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', help_text='Main heading shown in the hero section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_hi',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', help_text='Main heading shown in the hero section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_title_kn',
            field=models.CharField(default='Welcome to Kalyaneshwer Temple', help_text='Main heading shown in the hero section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='secondary_button_link',
            field=models.CharField(default='/about/', help_text='URL for the secondary button', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='secondary_button_text',
            field=models.CharField(default='Learn More', help_text='Text for the secondary button', max_length=50),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='secondary_button_text_en',
            field=models.CharField(default='Learn More', help_text='Text for the secondary button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='secondary_button_text_hi',
            field=models.CharField(default='Learn More', help_text='Text for the secondary button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='secondary_button_text_kn',
            field=models.CharField(default='Learn More', help_text='Text for the secondary button', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_text',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', help_text='Body text for the donation section'),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_text_en',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', help_text='Body text for the donation section', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_text_hi',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', help_text='Body text for the donation section', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_text_kn',
            field=models.TextField(default='Your generous donations help us maintain the temple, perform daily rituals, and support our charitable activities.', help_text='Body text for the donation section', null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_title',
            field=models.CharField(default='Support Our Mission', help_text='Heading for the donation section', max_length=200),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_title_en',
            field=models.CharField(default='Support Our Mission', help_text='Heading for the donation section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_title_hi',
            field=models.CharField(default='Support Our Mission', help_text='Heading for the donation section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='support_title_kn',
            field=models.CharField(default='Support Our Mission', help_text='Heading for the donation section', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, help_text='Description shown on the website'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description shown on the website', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Description shown on the website', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_kn',
            field=models.TextField(blank=True, help_text='Description shown on the website', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a photo for this service', null=True, upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(help_text='Name of the puja or service', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_en',
            field=models.CharField(help_text='Name of the puja or service', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_hi',
            field=models.CharField(help_text='Name of the puja or service', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_kn',
            field=models.CharField(help_text='Name of the puja or service', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='key',
            field=models.CharField(help_text="e.g., 'email', 'phone', 'address'", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description',
            field=models.TextField(blank=True, help_text='Brief description or bio'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description_en',
            field=models.TextField(blank=True, help_text='Brief description or bio', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description_hi',
            field=models.TextField(blank=True, help_text='Brief description or bio', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='description_kn',
            field=models.TextField(blank=True, help_text='Brief description or bio', null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='icon',
            field=models.CharField(default='fa-solid fa-user', help_text="Fallback FontAwesome icon if no photo (e.g., 'fa-solid fa-user-tie')", max_length=50),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(help_text='Full name of the trust member', max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_en',
            field=models.CharField(help_text='Full name of the trust member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_hi',
            field=models.CharField(help_text='Full name of the trust member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name_kn',
            field=models.CharField(help_text='Full name of the trust member', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(help_text="Their role (e.g., 'President', 'Chief Priest')", max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(help_text="Their role (e.g., 'President', 'Chief Priest')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_hi',
            field=models.CharField(help_text="Their role (e.g., 'President', 'Chief Priest')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role_kn',
            field=models.CharField(help_text="Their role (e.g., 'President', 'Chief Priest')", max_length=100, null=True),
        ),
    ]
